### crear producto

POST http://localhost:5500/api/productos/new
Content-Type: application/json

{
    "nombre": "mochila",
    "precio": 2000,
    "descripcion": "Mochila fea"
}

###

GET http://localhost:5500/api/productos/

###

GET http://localhost:5500/api/productos/61d660081d68aac562a58076

###